#pragma once

#include <mlibc/sysdep-signatures.hpp>

namespace mlibc {

struct YakSysdepTags : LibcPanic,
                       LibcLog,
                       Isatty,
                       Write,
                       TcbSet,
                       AnonAllocate,
                       AnonFree,
                       Seek,
                       Exit,
                       Close,
                       FutexWake,
                       FutexWait,
                       Read,
                       Open,
                       Openat,
                       Stat,
                       VmMap,
                       VmUnmap,
                       ClockGet,
                       GetGid,
                       GetEgid,
                       GetUid,
                       GetEuid,
                       GetPid,
                       GetPpid,
                       GetPgid,
                       GetSid,
                       SetPgid,
                       SetSid,
                       Sleep,
                       Dup,
                       Dup2,
                       Fork,
                       Execve,
                       Sigaction,
                       Fallocate,
                       Sigprocmask,
                       Kill,
                       Fcntl,
                       Ioctl,
                       Tcgetattr,
                       Tcsetattr,
                       Tcgetwinsize,
                       Tcsetwinsize,
                       Chdir,
                       Fchdir,
                       ReadEntries,
                       Faccessat,
                       Access,
                       Waitpid,
                       Ppoll,
                       Poll,
                       Pselect,
                       OpenDir,
                       Readlinkat,
                       Readlink,
                       Linkat,
                       Link,
                       Symlink,
                       Symlinkat,
                       Pread,
                       Pwrite,
                       VmProtect {};

template <typename Tag>
using Sysdeps = SysdepOf<YakSysdepTags, Tag>;

} // namespace mlibc
